/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UnauthenticatedSignupRouteImport } from './routes/_unauthenticated/signup'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPredictionsRouteImport } from './routes/_authenticated/predictions'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as UnauthenticatedSignupIndexRouteImport } from './routes/_unauthenticated/signup/index'
import { Route as UnauthenticatedLoginIndexRouteImport } from './routes/_unauthenticated/login/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/_home/index'
import { Route as UnauthenticatedSignupSsoCallbackRouteImport } from './routes/_unauthenticated/signup/sso-callback'
import { Route as UnauthenticatedLoginSsoCallbackRouteImport } from './routes/_unauthenticated/login/sso-callback'
import { Route as UnauthenticatedLoginContinueRouteImport } from './routes/_unauthenticated/login/continue'
import { Route as AuthenticatedLeaguesLeagueRouteImport } from './routes/_authenticated/leagues/$league'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedSignupRoute = UnauthenticatedSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPredictionsRoute =
  AuthenticatedPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedSignupIndexRoute =
  UnauthenticatedSignupIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UnauthenticatedSignupRoute,
  } as any)
const UnauthenticatedLoginIndexRoute =
  UnauthenticatedLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedSignupSsoCallbackRoute =
  UnauthenticatedSignupSsoCallbackRouteImport.update({
    id: '/sso-callback',
    path: '/sso-callback',
    getParentRoute: () => UnauthenticatedSignupRoute,
  } as any)
const UnauthenticatedLoginSsoCallbackRoute =
  UnauthenticatedLoginSsoCallbackRouteImport.update({
    id: '/login/sso-callback',
    path: '/login/sso-callback',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedLoginContinueRoute =
  UnauthenticatedLoginContinueRouteImport.update({
    id: '/login/continue',
    path: '/login/continue',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedLeaguesLeagueRoute =
  AuthenticatedLeaguesLeagueRouteImport.update({
    id: '/leagues/$league',
    path: '/leagues/$league',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AuthenticatedAboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/signup': typeof UnauthenticatedSignupRouteWithChildren
  '/leagues/$league': typeof AuthenticatedLeaguesLeagueRoute
  '/login/continue': typeof UnauthenticatedLoginContinueRoute
  '/login/sso-callback': typeof UnauthenticatedLoginSsoCallbackRoute
  '/signup/sso-callback': typeof UnauthenticatedSignupSsoCallbackRoute
  '/': typeof AuthenticatedHomeIndexRoute
  '/login': typeof UnauthenticatedLoginIndexRoute
  '/signup/': typeof UnauthenticatedSignupIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AuthenticatedAboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/leagues/$league': typeof AuthenticatedLeaguesLeagueRoute
  '/login/continue': typeof UnauthenticatedLoginContinueRoute
  '/login/sso-callback': typeof UnauthenticatedLoginSsoCallbackRoute
  '/signup/sso-callback': typeof UnauthenticatedSignupSsoCallbackRoute
  '/': typeof AuthenticatedHomeIndexRoute
  '/login': typeof UnauthenticatedLoginIndexRoute
  '/signup': typeof UnauthenticatedSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/predictions': typeof AuthenticatedPredictionsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_unauthenticated/signup': typeof UnauthenticatedSignupRouteWithChildren
  '/_authenticated/leagues/$league': typeof AuthenticatedLeaguesLeagueRoute
  '/_unauthenticated/login/continue': typeof UnauthenticatedLoginContinueRoute
  '/_unauthenticated/login/sso-callback': typeof UnauthenticatedLoginSsoCallbackRoute
  '/_unauthenticated/signup/sso-callback': typeof UnauthenticatedSignupSsoCallbackRoute
  '/_authenticated/_home/': typeof AuthenticatedHomeIndexRoute
  '/_unauthenticated/login/': typeof UnauthenticatedLoginIndexRoute
  '/_unauthenticated/signup/': typeof UnauthenticatedSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/dashboard'
    | '/leaderboard'
    | '/predictions'
    | '/profile'
    | '/signup'
    | '/leagues/$league'
    | '/login/continue'
    | '/login/sso-callback'
    | '/signup/sso-callback'
    | '/'
    | '/login'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dashboard'
    | '/leaderboard'
    | '/predictions'
    | '/profile'
    | '/leagues/$league'
    | '/login/continue'
    | '/login/sso-callback'
    | '/signup/sso-callback'
    | '/'
    | '/login'
    | '/signup'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/about'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/predictions'
    | '/_authenticated/profile'
    | '/_unauthenticated/signup'
    | '/_authenticated/leagues/$league'
    | '/_unauthenticated/login/continue'
    | '/_unauthenticated/login/sso-callback'
    | '/_unauthenticated/signup/sso-callback'
    | '/_authenticated/_home/'
    | '/_unauthenticated/login/'
    | '/_unauthenticated/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/signup': {
      id: '/_unauthenticated/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthenticatedSignupRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/predictions': {
      id: '/_authenticated/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AuthenticatedPredictionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/signup/': {
      id: '/_unauthenticated/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof UnauthenticatedSignupIndexRouteImport
      parentRoute: typeof UnauthenticatedSignupRoute
    }
    '/_unauthenticated/login/': {
      id: '/_unauthenticated/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginIndexRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/_home/': {
      id: '/_authenticated/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/signup/sso-callback': {
      id: '/_unauthenticated/signup/sso-callback'
      path: '/sso-callback'
      fullPath: '/signup/sso-callback'
      preLoaderRoute: typeof UnauthenticatedSignupSsoCallbackRouteImport
      parentRoute: typeof UnauthenticatedSignupRoute
    }
    '/_unauthenticated/login/sso-callback': {
      id: '/_unauthenticated/login/sso-callback'
      path: '/login/sso-callback'
      fullPath: '/login/sso-callback'
      preLoaderRoute: typeof UnauthenticatedLoginSsoCallbackRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/login/continue': {
      id: '/_unauthenticated/login/continue'
      path: '/login/continue'
      fullPath: '/login/continue'
      preLoaderRoute: typeof UnauthenticatedLoginContinueRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/leagues/$league': {
      id: '/_authenticated/leagues/$league'
      path: '/leagues/$league'
      fullPath: '/leagues/$league'
      preLoaderRoute: typeof AuthenticatedLeaguesLeagueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPredictionsRoute: typeof AuthenticatedPredictionsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedLeaguesLeagueRoute: typeof AuthenticatedLeaguesLeagueRoute
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPredictionsRoute: AuthenticatedPredictionsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedLeaguesLeagueRoute: AuthenticatedLeaguesLeagueRoute,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedSignupRouteChildren {
  UnauthenticatedSignupSsoCallbackRoute: typeof UnauthenticatedSignupSsoCallbackRoute
  UnauthenticatedSignupIndexRoute: typeof UnauthenticatedSignupIndexRoute
}

const UnauthenticatedSignupRouteChildren: UnauthenticatedSignupRouteChildren = {
  UnauthenticatedSignupSsoCallbackRoute: UnauthenticatedSignupSsoCallbackRoute,
  UnauthenticatedSignupIndexRoute: UnauthenticatedSignupIndexRoute,
}

const UnauthenticatedSignupRouteWithChildren =
  UnauthenticatedSignupRoute._addFileChildren(
    UnauthenticatedSignupRouteChildren,
  )

interface UnauthenticatedRouteChildren {
  UnauthenticatedSignupRoute: typeof UnauthenticatedSignupRouteWithChildren
  UnauthenticatedLoginContinueRoute: typeof UnauthenticatedLoginContinueRoute
  UnauthenticatedLoginSsoCallbackRoute: typeof UnauthenticatedLoginSsoCallbackRoute
  UnauthenticatedLoginIndexRoute: typeof UnauthenticatedLoginIndexRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedSignupRoute: UnauthenticatedSignupRouteWithChildren,
  UnauthenticatedLoginContinueRoute: UnauthenticatedLoginContinueRoute,
  UnauthenticatedLoginSsoCallbackRoute: UnauthenticatedLoginSsoCallbackRoute,
  UnauthenticatedLoginIndexRoute: UnauthenticatedLoginIndexRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
