/* These are constantized for now to limit API calls to avoid rate limiting
 *  but they should be fetched from the API in the future */

import { Sportsbook } from '@/types/sportsbook'

export const sportsbooks: Sportsbook[] = [
  {
    id: '888sport_ontario',
    name: '888sport (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'bally_bet',
    name: 'Bally Bet',
    state: null,
    country: null,
    fantasy: false,
    sgp: true,
    clone: {
      id: 'bally_bet_colorado',
      name: 'Bally Bet (Colorado)',
      state: 'Colorado',
      country: 'United States',
    },
  },
  {
    id: 'bally_bet_colorado',
    name: 'Bally Bet (Colorado)',
    state: 'Colorado',
    country: 'United States',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'betmgm_colorado',
    name: 'BetMGM (Colorado)',
    state: 'Colorado',
    country: 'United States',
    fantasy: false,
    sgp: false,
    clone: {
      id: 'betmgm_ontario',
      name: 'BetMGM (Ontario)',
      state: 'Ontario',
      country: 'Canada',
    },
  },
  {
    id: 'betmgm_ontario',
    name: 'BetMGM (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'betonline',
    name: 'BetOnline',
    state: null,
    country: null,
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'betonline_prop_builder',
    name: 'BetOnline (Prop Builder)',
    state: null,
    country: null,
    fantasy: false,
    sgp: true,
    clone: {
      id: 'bovada_prop_builder',
      name: 'Bovada (Prop Builder)',
      state: null,
      country: 'United States',
    },
  },
  {
    id: 'betrivers',
    name: 'BetRivers',
    state: null,
    country: null,
    fantasy: false,
    sgp: true,
    clone: {
      id: 'betrivers_ontario',
      name: 'BetRivers (Ontario)',
      state: 'Ontario',
      country: 'Canada',
    },
  },
  {
    id: 'betrivers_colorado',
    name: 'BetRivers (Colorado)',
    state: 'Colorado',
    country: 'United States',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'betrivers_ontario',
    name: 'BetRivers (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'betfair_united_kingdom',
    name: 'Betfair (United Kingdom)',
    state: null,
    country: 'United Kingdom',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'betfred_united_kingdom',
    name: 'Betfred (United Kingdom)',
    state: null,
    country: 'United Kingdom',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'betsafe_ontario',
    name: 'Betsafe (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'bodog',
    name: 'Bodog',
    state: null,
    country: 'Canada',
    fantasy: false,
    sgp: true,
    clone: {
      id: 'bovada',
      name: 'Bovada',
      state: null,
      country: 'United States',
    },
  },
  {
    id: 'bodog_prop_builder',
    name: 'Bodog (Prop Builder)',
    state: null,
    country: 'Canada',
    fantasy: false,
    sgp: true,
    clone: {
      id: 'bovada_prop_builder',
      name: 'Bovada (Prop Builder)',
      state: null,
      country: 'United States',
    },
  },
  {
    id: 'boombet_australia',
    name: 'BoomBet (Australia)',
    state: null,
    country: 'Australia',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'bovada',
    name: 'Bovada',
    state: null,
    country: 'United States',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'bovada_prop_builder',
    name: 'Bovada (Prop Builder)',
    state: null,
    country: 'United States',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'caesars_colorado',
    name: 'Caesars (Colorado)',
    state: 'Colorado',
    country: 'United States',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'caesars_ontario',
    name: 'Caesars (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'casumo_ontario',
    name: 'Casumo (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'circa_sports_nevada',
    name: 'Circa Sports (Nevada)',
    state: 'Nevada',
    country: 'United States',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'draftkings',
    name: 'DraftKings',
    state: null,
    country: null,
    fantasy: false,
    sgp: true,
    clone: {
      id: 'draftkings_ontario',
      name: 'DraftKings (Ontario)',
      state: 'Ontario',
      country: 'Canada',
    },
  },
  {
    id: 'draftkings_ontario',
    name: 'DraftKings (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'draftkings_pick6',
    name: 'DraftKings (Pick6)',
    state: null,
    country: null,
    fantasy: true,
    sgp: false,
    clone: null,
  },
  {
    id: 'espn_bet',
    name: 'ESPN BET',
    state: null,
    country: 'United States',
    fantasy: false,
    sgp: true,
    clone: {
      id: 'thescore_bet_ontario',
      name: 'theScore Bet (Ontario)',
      state: 'Ontario',
      country: 'Canada',
    },
  },
  {
    id: 'fanduel',
    name: 'FanDuel',
    state: null,
    country: 'United States',
    fantasy: false,
    sgp: true,
    clone: {
      id: 'fanduel_ontario',
      name: 'FanDuel (Ontario)',
      state: 'Ontario',
      country: 'Canada',
    },
  },
  {
    id: 'fanduel_ontario',
    name: 'FanDuel (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'fanatics',
    name: 'Fanatics',
    state: null,
    country: 'United States',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'fliff',
    name: 'Fliff',
    state: null,
    country: null,
    fantasy: true,
    sgp: false,
    clone: null,
  },
  {
    id: 'hard_rock_bet',
    name: 'Hard Rock Bet',
    state: null,
    country: 'United States',
    fantasy: false,
    sgp: true,
    clone: {
      id: 'hard_rock_bet_new_jersey',
      name: 'Hard Rock Bet (New Jersey)',
      state: 'New Jersey',
      country: 'United States',
    },
  },
  {
    id: 'hard_rock_bet_new_jersey',
    name: 'Hard Rock Bet (New Jersey)',
    state: 'New Jersey',
    country: 'United States',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'hotstreak',
    name: 'HotStreak',
    state: null,
    country: null,
    fantasy: true,
    sgp: false,
    clone: null,
  },
  {
    id: 'ladbrokes_australia',
    name: 'Ladbrokes (Australia)',
    state: null,
    country: 'Australia',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'ladbrokes_united_kingdom',
    name: 'Ladbrokes (United Kingdom)',
    state: null,
    country: 'United Kingdom',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'northstar_bets_ontario',
    name: 'NorthStar Bets (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'ps3838',
    name: 'PS3838',
    state: null,
    country: null,
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'paddy_power_united_kingdom',
    name: 'Paddy Power (United Kingdom)',
    state: null,
    country: 'United Kingdom',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'parlayplay',
    name: 'ParlayPlay',
    state: null,
    country: null,
    fantasy: true,
    sgp: false,
    clone: null,
  },
  {
    id: 'pinnacle',
    name: 'Pinnacle',
    state: null,
    country: null,
    fantasy: false,
    sgp: false,
    clone: {
      id: 'ps3838',
      name: 'PS3838',
      state: null,
      country: null,
    },
  },
  {
    id: 'pointsbet',
    name: 'PointsBet',
    state: null,
    country: null,
    fantasy: false,
    sgp: false,
    clone: {
      id: 'pointsbet_ontario',
      name: 'PointsBet (Ontario)',
      state: 'Ontario',
      country: 'Canada',
    },
  },
  {
    id: 'pointsbet_ontario',
    name: 'PointsBet (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'prime_sports_new_jersey',
    name: 'Prime Sports (New Jersey)',
    state: 'New Jersey',
    country: 'United States',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'prizepicks',
    name: 'PrizePicks',
    state: null,
    country: null,
    fantasy: true,
    sgp: true,
    clone: null,
  },
  {
    id: 'prizepicks_demons',
    name: 'PrizePicks (Demons)',
    state: null,
    country: null,
    fantasy: true,
    sgp: true,
    clone: null,
  },
  {
    id: 'prizepicks_goblins',
    name: 'PrizePicks (Goblins)',
    state: null,
    country: null,
    fantasy: true,
    sgp: true,
    clone: null,
  },
  {
    id: 'prophetx',
    name: 'ProphetX',
    state: null,
    country: 'United States',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'sky_bet_united_kingdom',
    name: 'Sky Bet (United Kingdom)',
    state: null,
    country: 'United Kingdom',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'sleeper',
    name: 'Sleeper',
    state: null,
    country: null,
    fantasy: true,
    sgp: false,
    clone: null,
  },
  {
    id: 'stake',
    name: 'Stake',
    state: null,
    country: null,
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'tab_australia',
    name: 'TAB (Australia)',
    state: null,
    country: 'Australia',
    fantasy: false,
    sgp: false,
    clone: null,
  },
  {
    id: 'underdog_fantasy',
    name: 'Underdog Fantasy',
    state: null,
    country: null,
    fantasy: true,
    sgp: false,
    clone: null,
  },
  {
    id: 'unibet_united_kingdom',
    name: 'Unibet (United Kingdom)',
    state: null,
    country: 'United Kingdom',
    fantasy: false,
    sgp: true,
    clone: null,
  },
  {
    id: 'thescore_bet',
    name: 'theScore Bet',
    state: null,
    country: 'United States',
    fantasy: false,
    sgp: true,
    clone: {
      id: 'thescore_bet_ontario',
      name: 'theScore Bet (Ontario)',
      state: 'Ontario',
      country: 'Canada',
    },
  },
  {
    id: 'thescore_bet_ontario',
    name: 'theScore Bet (Ontario)',
    state: 'Ontario',
    country: 'Canada',
    fantasy: false,
    sgp: true,
    clone: null,
  },
]
